Options:

  #Put your desired material that the schematic blocks should be made of
  #It can not be an item (Like a door or torch)
  material: BEDROCK

  #Amount of time player gets to preview the schematic before
  #cancellation (In seconds)
  preview-time: 10

  #Any schematic names listed within the brackets will require a
  #permission node to use
  #Ex: If you wanted schematic castle to have the perm node
  #in.castle you'd put castle (CASE-SENSITIVE)
  permissions: []

  #Size of the radius to be checked around the schematic
  #during placement
  check-radius: 15

  #If enabled schematics will be placed gradually
  block-by-block: true

  #If block-by-block is enabled this designates the
  #speed per second
  blocksPerSecond: 7

  #Sign name to be displayed
  sign-name: §b[§eiN_Blocks§b]

  #Use item lore instead of block name?
  use-lore: false