name: iN_Blocks
version: 1.6
main: creeoer.plugins.in_blocks.main.iN_Blocks
author: Creeoer
depend: [WorldEdit]
softdepend: [Vault, PreciousStones, Factions, WorldGuard, GriefPrevention, Towny, RedProtect, MassiveCore]


commands:
   in:
     description: iN_Block commands
     usage: "§bUsage: /in [give/create/delete/list]"
